作業目標<br>
活用矩陣運算，實做線性代數<br>

作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]), 即表示 <br>
$$
\text{array1} = 
 \left[
 \begin{matrix}
   10 & 8 \\
   3 & 5
  \end{matrix}
  \right] 
$$

1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.18.5


In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

inv_array1 = np.linalg.inv( array1 )
print( '反矩陣 = \n', inv_array1 )

反矩陣 = 
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [3]:
print( inv_array1 @ array1 )
print( array1 @ inv_array1 )

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [4]:
#2. 運用上列array計算特徵值、特徵向量?

v, w = np.linalg.eig(array1)

print( '特徵值=', v, '\n' )
print( '特徵向量= \n', w )

特徵值= [13.  2.] 

特徵向量= 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [5]:
#3. 運用上列array計算SVD?

np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))