作業目標<br>
讀取存取陣列資料<br>

作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.18.5


In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

print( array1 )
print( array2 )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [3]:
np.savez( 'Array12.npz', element1=array1, element2=array2 )

In [4]:
#2. 讀取剛剛的npz檔，加入新的array一起存成新的npz檔

load_array = np.load( 'Array12.npz' )
load_array.files

['element1', 'element2']

In [5]:
# 新的array
array3 = np.ones( (3,4), dtype=int )
array3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# 儲存新的 npz 檔
np.savez( 'Array123.npz', element1=load_array['element1'], element2=load_array['element2'], element3=array3 )

In [7]:
# 讀取新的 npz 檔
load_array_2 = np.load( 'Array123.npz' )

print( '新的 npz 檔內容: ', load_array_2.files, '\n' ) 
print( '新的 npz 檔中第一個元素內容: \n', load_array_2['element1'], '\n' )
print( '新的 npz 檔中第二個元素內容: \n', load_array_2['element2'], '\n' )
print( '新的 npz 檔中第三個元素內容: \n', load_array_2['element3'] )

新的 npz 檔內容:  ['element1', 'element2', 'element3'] 

新的 npz 檔中第一個元素內容: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

新的 npz 檔中第二個元素內容: 
 [2 3 5] 

新的 npz 檔中第三個元素內容: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
