# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.random.randint(10, size=6) 

print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())



list(a):  [3, 1, 4, 7, 4, 5]
a.tolist():  [3, 1, 4, 7, 4, 5]
list(b):  [array([8, 1]), array([7, 5]), array([3, 9])]
b.tolist():  [[8, 1], [7, 5], [3, 9]]


In [12]:
'''
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。
'''

'\nlist(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；tolist() 才能達成多層的型態轉換。\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
# 參考解答

import numpy as np

a = np.random.randint(10, size=6) 

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[9 8 0 0 5 5]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [5]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[2 9 5 0]
 [4 3 3 5]
 [0 0 2 8]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [6]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[3 9]
  [4 1]
  [8 2]]

 [[5 2]
  [4 3]
  [9 1]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [7]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 4, 4, 5, 4, 7]
[7, 4, 4, 5, 4, 7]


In [8]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 3, 6, 2], [9, 3, 9, 2], [6, 5, 8, 1]]
[array([9, 3, 6, 2]), array([9, 3, 9, 2]), array([6, 5, 8, 1])]


In [9]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 6], [1, 9], [4, 6]], [[3, 9], [0, 5], [3, 8]]]
[array([[7, 6],
       [1, 9],
       [4, 6]]), array([[3, 9],
       [0, 5],
       [3, 8]])]


In [10]:
## 簡單版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 4, 4, 5, 4, 7]
[[9, 3, 6, 2], [9, 3, 9, 2], [6, 5, 8, 1]]
[[[7, 6], [1, 9], [4, 6]], [[3, 9], [0, 5], [3, 8]]]


In [11]:
## 進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 4, 4, 5, 4, 7]
[[9, 3, 6, 2], [9, 3, 9, 2], [6, 5, 8, 1]]
[[[7, 6], [1, 9], [4, 6]], [[3, 9], [0, 5], [3, 8]]]
