# 範例
***

# [教學目標]

* 了解並且學會使用陣列中的統計方法
* 了解並且學會使用陣列中的搜尋與排序方法
* 了解並且學會使用陣列中的形狀方法



In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1


In [2]:
# 陣列中的統計方法


a = np.arange(6)
print(a)

print(a.sum()) 
print(a.min()) 
print(a.max()) 


[0 1 2 3 4 5]
15
0
5


In [3]:
# 一種功能，三種函式


a = np.arange(6)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


In [5]:
# 陣列中的軸參數

b = np.arange(12).reshape(3, 4)

print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))


66
[12 15 18 21]
[ 6 22 38]


In [7]:
# 搜尋與排序方法

import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(a.sort())
print(a)



None
[1 2 3 4 5]


In [8]:
import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(np.sort(a))
print(a)


[1 2 3 4 5]
[1 3 2 5 4]


In [10]:
import numpy as np 

print(np.searchsorted([1,2,3,4,5], 3))
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [-10, 10, 3, 5]
))



2
[0 5 2 4]


In [11]:
# reshape 和 resize

import numpy as np 

a = np.arange(6)

print(a)
print(a.reshape(3, 2))
print(a)


[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [12]:
import numpy as np 

a = np.arange(6)

print(a)
print(a.resize((3, 2)))
print(a)


None
[[0 1]
 [2 3]
 [4 5]]


In [1]:
# 三種陣列攤平用法

import numpy as np 

a = np.arange(6).reshape((3, 2))

print(a.ravel() )
print(a.flatten())
print(a.flat)
print(list(a.flat))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
