# 範例
***

# [教學目標]

* 正確的使用 NumPy 中的算術運算
* 了解 NumPy 陣列與數學矩陣的關係
* 知道 NumPy 與 SciPy 差異為何


In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1


In [2]:
# 相同大小的陣列運算

import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a + b)
print(a * b)

[20 31 42 53]
[  0  30  80 150]


In [3]:
# 常數與陣列運算

import numpy as np

a = np.array( [20,30,40,50] )

print(a - 2)
print(a / 10)


[18 28 38 48]
[2. 3. 4. 5.]


In [4]:
# 不同大小的陣列運算

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

print(data + ones_row)


[[2 3]
 [4 5]
 [6 7]]


In [5]:
# 陣列運算與容器運算的差異

a = np.array( [20,30,40,50] )
print(a + 1)

a = [20, 30, 40, 50]
b = []
for i in a:
    b.append(i+1)
print(b)


[21 31 41 51]
[21, 31, 41, 51]


In [6]:
# 用於陣列的矩陣運算

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
y = np.array([[5.], [7.]])
print(y)

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]


In [7]:
print(a.transpose())
print(np.linalg.inv(a))
print(np.trace(a))
print(np.linalg.solve(a, y))


[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]
