# 範例
***

# [教學目標]

* 知道如何使用 DataFrame 中的運算
* 了解 DataFrame 運算的特性
* 知道 DataFrame 中統計與字串的操作




In [1]:
# 載入 NumPy, Pandas 套件
import numpy as np
import pandas as pd

# 檢查正確載入與版本
print(np)
print(np.__version__)
print(pd)
print(pd.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1
<module 'pandas' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/pandas/__init__.py'>
0.23.1


In [2]:
# 相同欄位的算術運算

import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]])
df2 = pd.DataFrame([[1, 1, 1]])

print(df1 + df2)
print(df1 - df2)
print(df1 * df2)
print(df1 / df2)


   0  1  2
0  2  3  4
   0  1  2
0  0  1  2
   0  1  2
0  1  2  3
     0    1    2
0  1.0  2.0  3.0


In [3]:
# 不同欄位的算術運算

import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]], columns=['a', 'b', 'c'])
df2 = pd.DataFrame([[1, 1, 1]], columns=['c', 'd', 'e'])

print(df1 + df2)
#        a       b      c     d       e
# 0 NaN NaN     4 NaN NaN


    a   b  c   d   e
0 NaN NaN  4 NaN NaN


In [4]:
# DataFrame 也有廣播的特性

import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]])

print(df1 + 1)
#    0  1  2
# 0  2  3  4


   0  1  2
0  2  3  4


In [7]:
# DataFrame 和 Array 有點不一樣

import pandas as pd

df = pd.DataFrame([[1, 2, 3]])

print(df + 1)
#    0  1  2
# 0  2  3  4
print(df + pd.DataFrame([1]))
#    0   1   2
# 0  2 NaN NaN



   0  1  2
0  2  3  4
   0   1   2
0  2 NaN NaN


In [8]:
import numpy as np

a = np.array([[1, 2, 3]])

print(a + 1)
# [[2 3 4]]

print(a + np.array([1]))
# [[2 3 4]]



[[2 3 4]]
[[2 3 4]]


In [10]:
# DataFrame 也有遮罩運算

print(df > 2)
#        A      B     C
# a  False  False  True
# b   True   True  True

print(df[df > 2])
#      A    B  C
# a  NaN  NaN  3
# b  4.0  5.0  6



       0      1     2
0  False  False  True
    0   1  2
0 NaN NaN  3


In [11]:

print(df['A'] > 2)
# a    False
# b     True
# Name: A, dtype: bool

print(df[df['A'] > 2])
#    A  B  C
# b  4  5  6


KeyError: 'A'

In [15]:
# DataFrame 中的排序

import pandas as pd

df = pd.DataFrame({
    'col1': ['A', 'a', 'B', 'B', 'B', 'b'],
    'col2': [2, 1, 2, 3, 1, 8],
})

df.sort_values(by=['col1'])


col1  col2
0    A     2
2    B     2
3    B     3
4    B     1
1    a     1
5    b     8

In [16]:
df.sort_values(by=['col1', 'col2'])


col1  col2
0    A     2
4    B     1
2    B     2
3    B     3
1    a     1
5    b     8

In [17]:
df.sort_values(by='col2', ascending=False)


col1  col2
5    b     8
3    B     3
0    A     2
2    B     2
1    a     1
4    B     1