# 範例
***

# [教學目標]

* 認識 NumPy 中提供的資料型態
* 了解各種型態的差異與定義
* 正確的比較型態判斷



In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1


In [2]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 陣列的常用屬性

print(a.dtype) # int64
print(a.itemsize) # 8


int64
8


In [4]:
# numpy 中的型態判斷

print(a.dtype == 'int64') 
print(a.dtype is 'int64') 
print(a.dtype is np.int64) 


True
False
False


In [5]:
# 資料型態的正確用法

print(a.dtype == 'int64') # True
print(a.dtype == np.int64) # True
print(a.dtype is np.dtype('int64')) # True


True
True
True
